kind: Service
apiVersion: v1
metadata:
  namespace: test-rabbitmq
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer  
spec:
  type: NodePort
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    protocol: TCP
    nodePort: 31672
  selector:
    app: rabbitmq
